---
title: "Schedule"
---

A schedule of topics and readings is provided below. Each week will cover a single topic or group of topics. You should treat the readings as a reference and as a more detailed exposition of the topics discussed in lecture. Consult the readings when you want to know more or want a slightly different approach to explaining a particular topic.

Monday lectures will typically introduce the core theory for the week's topic while Wednesday lectures will go into greater detail and work through applications. You should make sure to review the readings prior to that week's lectures with an aim towards completing them before Wednesday's lecture.

All hyperlinks to papers are either to the published version of the paper (if published) or to the working paper. You should use your university library access to obtain the full version if the article is not open access. Likewise, textbook readings will be to the free/open version of the book (if available) or to the UW-Madison university library eBook.

::: {.callout-note appearance="simple"}
There is **no class during the first week of instruction** due to APSA and Labor Day (September 2 and 7). The course begins on Wednesday, September 9.
:::

## Week 1: Course Introduction and Review

*Wednesday, September 9*

**Topics:**

- What is a statistical model and what is it good for?
- Review of estimands, estimators and their properties
- Review of linear regression

**Readings:**

- **Review:** Chapters 1-7; Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. [*Regression and Other Stories*.](https://avehtari.github.io/ROS-Examples/index.html) Cambridge: Cambridge University Press.

::: {.callout-note appearance="simple"}
**Problem Set 1** assigned Wednesday, September 9 -- due Wednesday, September 23.
:::

---

## Week 2: Introduction to Likelihood Inference

*Monday, September 14 & Wednesday, September 16*

**Topics:**

- What is a "parametric" model?
- The likelihood function
- Maximum likelihood estimation

**Readings:**

- Chapter 5 ("Parametric Models"); Aronow, P. M. and Benjamin T. Miller. 2019 [*Foundations of Agnostic Statistics*](https://www.cambridge.org/core/books/foundations-of-agnostic-statistics/parametric-models/E101D209A3DD22F95E7853B64FB7257F)
- Chapter 6 ("Likelihood Inference"); Evans, Michael J., and Jeffrey S. Rosenthal. 2010. [*Probability and Statistics: The Science of Uncertainty*](https://utstat.toronto.edu/mikevans/jeffrosenthal/chapt6.pdf), 2nd ed. New York: W.H. Freeman.

---

## Week 3: Generalized Linear Models

*Monday, September 21 & Wednesday, September 23*

**Topics:**

- Properties of maximum likelihood estimators
- The generalized linear model framework
- Binary outcome models

**Readings:**

- Chapters 13-14; Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. [*Regression and Other Stories*.](https://avehtari.github.io/ROS-Examples/index.html) Cambridge: Cambridge University Press.

::: {.callout-note appearance="simple"}
**Problem Set 1** due Wednesday, September 23. **Problem Set 2** assigned Wednesday, September 23 -- due Wednesday, October 7.
:::

---

## Week 4: More Likelihood Models

*Monday, September 28 & Wednesday, September 30*

**Topics:**

- Duration models (parametric, semi-parametric (Cox) and non-parametric approaches)
- Event count models (Poisson regression and quasi-MLE methods)

**Readings:**

- Chapters 15; Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. [*Regression and Other Stories*.](https://avehtari.github.io/ROS-Examples/index.html) Cambridge: Cambridge University Press.
- Clark, T. G., M. J. Bradburn, S. B. Love, and D. G. Altman. 2003. ["Survival Analysis Part I: Basic Concepts and First Analyses."](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2394262/) *British Journal of Cancer* 89 (2): 232-238.
- Stensrud, Mats J., and Miguel A. Hernán. 2020. ["Why Test for Proportional Hazards?"](https://jamanetwork.com/journals/jama/fullarticle/2763185) *JAMA* 323 (14): 1401-1402.
- Chapter 8; Wooldridge, Jeffrey M. 1999. ["Quasi-Likelihood Methods for Count Data."](https://doi.org/10.1111/b.9780631216339.1999.00009.x) In *Handbook of Applied Econometrics*, vol. 2, 352-406.

---


## Week 5: Bayesian Inference

*Monday, October 5*

**Topics:**

- Principles of posterior inference
- How to write a Bayesian model
- Quantities of interest: posterior mode, posterior mean, credible intervals

**Readings:**

- Chapter 9; Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. [*Regression and Other Stories*.](https://avehtari.github.io/ROS-Examples/index.html) Cambridge: Cambridge University Press.
- Chapters 10-11; Gelman, Andrew, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin. 2013. [*Bayesian Data Analysis*.](http://www.stat.columbia.edu/~gelman/book/) 3rd ed. Boca Raton: Chapman and Hall/CRC.

::: {.callout-note appearance="simple"}
**Problem Set 2** due Wednesday, October 7. **Problem Set 3** assigned Wednesday, October 7 -- due Wednesday, October 21.
:::

---

::: {.callout-important appearance="simple"}
**Midterm 1** In-Class, Wednesday, October 7th
:::

---

## Week 6: Estimating Bayesian Models

*Monday, October 12 & Wednesday, October 14*

**Topics:**

- Analytically tractable solutions through conjugate priors
- Markov Chain Monte Carlo methods
- Introduction to MCMC in [Stan](https://mc-stan.org/)

**Readings:**

Chapters 3, 9. McElreath, Richard. 2020. [Statistical Rethinking: A Bayesian Course with Examples in R and Stan](https://learning-oreilly-com.ezproxy.library.wisc.edu/library/view/statistical-rethinking-2nd/9780429639142/) 2nd. ed.


---

## Week 7: Multilevel Regression Models

*Monday, October 19 & Wednesday, October 21*

**Topics:**

- Partial pooling through priors
- Methods for model validation
- Multilevel regression and post-stratification (MRP)

**Readings:**

- Chapters 9, 11, and Appendix A; Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2020. [*Regression and Other Stories*.](https://avehtari.github.io/ROS-Examples/index.html) Cambridge: Cambridge University Press.
- Chapter 15; Gelman, Andrew, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin. 2013. [*Bayesian Data Analysis*.](http://www.stat.columbia.edu/~gelman/book/) 3rd ed. Boca Raton: Chapman and Hall/CRC.
- Park, David K., Andrew Gelman, and Joseph Bafumi. 2004. ["Bayesian Multilevel Estimation with Poststratification: State-Level Estimates from National Polls."](https://doi.org/10.1093/pan/mph024) *Political Analysis* 12 (4): 375-385.

::: {.callout-note appearance="simple"}
**Problem Set 3** due Wednesday, October 21. **Problem Set 4** assigned Wednesday, October 21 -- due Wednesday, November 4.
:::

---

## Week 8: Mixture Models and the EM Algorithm

*Monday, October 26 & Wednesday, October 28*

**Topics:**

- Exploratory data analysis and clustering models
- MLE and MAP estimation via the "Expectation-Maximization" algorithm

**Readings:**

- Chapters 13 and 22; Gelman, Andrew, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin. 2013. [*Bayesian Data Analysis*.](http://www.stat.columbia.edu/~gelman/book/) 3rd ed. Boca Raton: Chapman and Hall/CRC.


---

## Week 9: Item Response Theory and Ideal Point Models

*Monday, November 2*

**Topics:**

- Latent trait models
- "Ideal point" models in legislative voting

**Readings:**

- Martin, Andrew D., and Kevin M. Quinn. 2002. ["Dynamic Ideal Point Estimation via Markov Chain Monte Carlo for the U.S. Supreme Court, 1953-1999."](https://doi.org/10.1093/pan/10.2.134) *Political Analysis* 10 (2): 134-153.
- Clinton, Joshua, Simon Jackman, and Douglas Rivers. 2004. ["The Statistical Analysis of Roll Call Data."](https://doi.org/10.1017/S0003055404001194) *American Political Science Review* 98 (2): 355-370.
- Imai, Kosuke, James Lo, and Jonathan Olmsted. ["Fast estimation of ideal points with massive data."](https://doi.org/10.1017/S000305541600037X) *American Political Science Review* 110, no. 4 (2016): 631-656.

---

::: {.callout-important appearance="simple"}
**Midterm 2** In-Class, Wednesday, November 4th
:::

---


## Week 10: Regularization and Model Selection

*Monday, November 9 & Wednesday, November 11*

**Topics:**

- Variable selection and penalized regression (Ridge, LASSO)
- Cross-fitting and out-of-sample validation

**Readings:**

- Chapters 6-7; James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. [*An Introduction to Statistical Learning*.](https://www.statlearning.com/) New York: Springer.

---

## Week 11: Flexible Regression -- Trees and Forests

*Monday, November 16 & Wednesday, November 18*

**Topics:**

- Regression trees
- Aggregation via sums of trees + regularization via BART
- Bagging, boosting, random forests

**Readings:**

- Chapter 8; James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. [*An Introduction to Statistical Learning*.](https://www.statlearning.com/) New York: Springer.
- Chapters 9-10 and 15; Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2009. [*The Elements of Statistical Learning: Data Mining, Inference, and Prediction*.](https://hastie.su.domains/ElemStatLearn/) 2nd ed. New York: Springer.
- Hill, Jennifer, Antonio Linero, and Jared Murray. 2020. ["Bayesian Additive Regression Trees: A Review and Look Forward."](https://doi.org/10.1146/annurev-statistics-031219-041110) *Annual Review of Statistics and Its Application* 7: 251-278.

---

## Week 12: Flexible Regression -- Kernels and Gaussian Processes

*Monday, November 23*

::: {.callout-important appearance="simple"}
Thanksgiving recess runs November 26-29. Class meets as usual on Monday this week.
:::

**Topics:**

- 
- Kernel ridge regression
- Gaussian process regression

**Readings:**

- Hainmueller, Jens, and Chad Hazlett. ["Kernel regularized least squares: Reducing misspecification bias with a flexible and interpretable machine learning approach."](https://doi.org/10.1093/pan/mpt019) *Political Analysis* 22, no. 2 (2014): 143-168.
- Chapters 2 and 4; Rasmussen, Carl Edward, and Christopher K. I. Williams. 2006. [*Gaussian Processes for Machine Learning*.](https://gaussianprocess.org/gpml/) Cambridge, MA: MIT Press.

---

## Week 13: Causal inference with flexible regression

*Monday, November 30 & Wednesday, December 2*

**Topics:**

- Efficient semiparametric estimation of statistical functionals
- Influence functions
- "Doubly-robust"/"Neyman-orthogonal" estimators

**Readings:**

- Fisher, Aaron, and Edward H. Kennedy. ["Visually communicating and teaching intuition for influence functions."](https://doi.org/10.1080/00031305.2020.1717620) *The American Statistician* 75, no. 2 (2021): 162-172.
- Kennedy, Edward H. 2024. ["Semiparametric Doubly Robust Targeted Double Machine Learning: A Review."](https://arxiv.org/abs/2203.06469) In *Handbook of Statistical Methods for Precision Medicine*, 207-236.

---

::: {.callout-important appearance="simple"}
**Poster Session** Friday, December 4th
:::

---

## Week 14: Neural networks

*Monday, December 7 & Wednesday, December 9*

**Topics:**

- Introduction to neural networks
- Estimation via stochastic gradient descent
- Supervised fine-tuning of pre-trained models

**Readings:**

- Chapter 10; James, Gareth, Daniela Witten, Trevor Hastie, and Robert Tibshirani. 2013. [*An Introduction to Statistical Learning*.](https://www.statlearning.com/) New York: Springer.


---
