---
title: "PS 818: Problem Set 2"
author: "YOUR NAME"
date: "September 23, 2026"
format:
  html:
    toc: true
    df-print: paged
    embed-resources: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Useful packages
library(tidyverse)
```

> **Assigned:** Wednesday, September 23, 2026. **Due:** Wednesday, October 7, 2026.
>
> Submit your solutions on **Gradescope**. Upload *both* the rendered `.html` file (saved as `Yourlastname_Yourfirstinitial_pset2.html`) and the `.qmd` source file that produced it (saved as `Yourlastname_Yourfirstinitial_pset2.qmd`). We should be able to run your code without error messages. In order to receive credit, homework submissions must be substantially started and all work must be shown.
>
> I recommend editing this `.qmd` file directly and rendering it to `.html` when you are done. Problem sets are graded on a (+/✓/-) scale.
>
> You are strongly encouraged to discuss the problems with other students, in person or on the course [Slack](https://uw-mpolscimethods.slack.com/), but each student must submit their own write-up and code. See the [Syllabus](https://www.antonstrezhnev.com/ps818/syllabus.html) for the full collaboration policy and for the course policy on generative large language models.

# Problem 1

Conjoint experiments are a popular method for learning about 

## Part A

# Problem 2

## Part A

# Problem 3

## Part A
